local test = require("test")
local auth = require("mcp_auth")
local config = require("keeper_config")
local tokens = require("mcp_tokens")
local sql = require("sql")
local consts = require("mcp_consts")
local hash = require("hash")
local handler = require("mcp_handler_core")
local migration_runner = require("migration_runner")

local function with_resolver(id, body)
    local saved = config.mcp_group_resolver
    config.mcp_group_resolver = function() return id, nil end
    local ok, err = pcall(body)
    config.mcp_group_resolver = saved
    if not ok then error(err) end
end

local function define_tests()
    test.describe("MCP host groups", function()
        test.before_all(function()
            local migrated = migration_runner.setup(consts.db_id()):run_next({
                allowed_ids = { "keeper.mcp.migrations:migration_06" },
            })
            test.eq(migrated.status, "complete")
            local db, err = sql.get(consts.db_id())
            test.is_nil(err)
            local _, table_err = db:execute("CREATE TABLE IF NOT EXISTS app_users (user_id TEXT PRIMARY KEY, status TEXT NOT NULL)")
            test.is_nil(table_err)
            local _, insert_err = sql.builder.insert("app_users"):set_map({ user_id = "member", status = "active" }):suffix("ON CONFLICT(user_id) DO NOTHING")
                :run_with(db):exec()
            test.is_nil(insert_err)
            local _, failure_err = sql.builder.insert("app_users"):set_map({ user_id = "failure", status = "active" })
                :suffix("ON CONFLICT(user_id) DO NOTHING"):run_with(db):exec()
            test.is_nil(failure_err)
            db:release()
        end)
        test.it("uses the host function injected through the optional requirement", function()
            local resolver, err = config.mcp_group_resolver()
            test.is_nil(err)
            test.eq(resolver, "app:mcp_group_resolver")
            local actor, actor_err = auth.admin_actor({ identity = "member" })
            test.is_nil(actor_err)
            test.eq(actor:meta().security_groups[1], "host:user")
        end)
        test.it("authenticates a bearer token with the host groups", function()
            with_resolver("app:mcp_group_resolver", function()
                local minted, mint_err = tokens.create({ identity = "member", label = "host-groups", scopes = { "app.ui" } })
                test.is_nil(mint_err)
                local session, session_err = auth.session_from_token(minted.token)
                test.is_nil(session_err)
                local actor, actor_err = auth.admin_actor(session)
                test.is_nil(actor_err)
                test.eq(actor:id(), "member")
                test.eq(#actor:meta().security_groups, 2)
                test.eq(actor:meta().security_groups[1], "host:user")
                test.eq(actor:meta().security_groups[2], "host:editors")
                local revoked, revoke_err = tokens.revoke(hash.sha256(minted.token))
                test.is_nil(revoke_err)
                test.not_nil(revoked)
            end)
        end)
        test.it("fails bearer authentication when the host directory fails", function()
            with_resolver("app:mcp_group_resolver", function()
                local minted, mint_err = tokens.create({ identity = "failure", label = "failed-host", scopes = { "app.ui" } })
                test.is_nil(mint_err)
                local session, err = auth.session_from_token(minted.token)
                local revoked, revoke_err = tokens.revoke(hash.sha256(minted.token))
                test.is_nil(revoke_err)
                test.is_true(revoked)
                test.is_nil(session)
                test.eq(err:kind(), errors.UNAVAILABLE)
            end)
        end)
        test.it("stamps the token subject's live groups on its actor", function()
            with_resolver("app:mcp_group_resolver", function()
                local actor, err = auth.admin_actor({ identity = "member", label = "member-token" })
                test.is_nil(err)
                test.not_nil(actor)
                test.eq(actor:id(), "member")
                test.eq(#actor:meta().security_groups, 2)
                test.eq(actor:meta().security_groups[1], "host:user")
                test.eq(actor:meta().security_groups[2], "host:editors")
                test.eq(actor:meta().via, "mcp")
                test.eq(actor:meta().token_label, "member-token")
            end)
        end)
        test.it("serializes typed resolver errors as JSON-RPC message strings", function()
            local payload
            local response = {
                set_status = function() end,
                write_json = function(_, value) payload = value end,
            }
            local req = { header = function() return nil end }
            local typed = errors.new({ message = "host directory unavailable", kind = errors.UNAVAILABLE })
            local ok = handler._bind_session(req, response, "initialize",
                { identity = "member", token_hash = "host-group-failure" }, 1, {},
                function() return nil, nil, typed end)
            test.is_false(ok)
            test.eq(type(payload.error.message), "string")
            test.eq(payload.error.message, tostring(typed))
        end)
        test.it("preserves the actor shape for an unbound host", function()
            with_resolver("", function()
                local actor, err = auth.admin_actor({ identity = "member", label = "unbound" })
                test.is_nil(err)
                test.is_nil(actor:meta().security_groups)
                test.eq(actor:meta().token_label, "unbound")
            end)
        end)
        test.it("resolves groups once within an authenticated request", function()
            local saved = config.mcp_group_resolver
            local calls = 0
            config.mcp_group_resolver = function()
                calls = calls + 1
                return "app:mcp_group_resolver", nil
            end
            local ok, err = pcall(function()
                local session = { identity = "member" }
                local actor, actor_err = auth.admin_actor(session)
                test.is_nil(actor_err)
                test.not_nil(actor)
                local allowed, denial = auth.session_allows(session, "registry.get", "keeper:definition")
                test.is_nil(denial)
                test.is_true(allowed)
                test.eq(calls, 1)
            end)
            config.mcp_group_resolver = saved
            if not ok then error(err) end
        end)
        test.it("accepts an active subject with no groups", function()
            with_resolver("app:mcp_group_resolver", function()
                local actor, err = auth.admin_actor({ identity = "empty" })
                test.is_nil(err)
                test.eq(#actor:meta().security_groups, 0)
            end)
        end)
        for _, identity in ipairs({ "failure", "malformed", "invalid-group", "sparse-groups" }) do
            test.it("fails authentication for " .. identity, function()
                with_resolver("app:mcp_group_resolver", function()
                    local actor, scope, err = auth.admin_identity({ identity = identity })
                    test.is_nil(actor)
                    test.is_nil(scope)
                    test.not_nil(err)
                    test.eq(err:kind(), errors.UNAVAILABLE)
                    test.eq(err:details().code, "KEEPER_MCP_GROUP_RESOLUTION_FAILED")
                    local allowed, denial = auth.session_allows({ identity = identity }, "registry.get", "keeper:definition")
                    test.is_false(allowed)
                    test.not_nil(denial)
                end)
            end)
        end
        test.it("denies an inactive host subject", function()
            with_resolver("app:mcp_group_resolver", function()
                local actor, err = auth.admin_actor({ identity = "inactive" })
                test.is_nil(actor)
                test.eq(err:kind(), errors.PERMISSION_DENIED)
            end)
        end)
        test.it("fails when the host resolver cannot be called", function()
            with_resolver("app:missing_resolver", function()
                local actor, err = auth.admin_actor({ identity = "member" })
                test.is_nil(actor)
                test.eq(err:kind(), errors.UNAVAILABLE)
            end)
        end)
    end)
end
return { run = test.run_cases(define_tests) }
