local test = require("test")

local kb_read = require("kb_read")
local kb_write = require("kb_write")

local function define_tests()
    describe("Knowledge Tools", function()
        describe("kb_read", function()
            it("requires action parameter", function()
                local result, err = kb_read.handler({})
                test.is_nil(result)
                test.not_nil(err)
            end)

            it("rejects unknown action", function()
                local result, err = kb_read.handler({ action = "invalid" })
                test.is_nil(result)
                test.not_nil(err)
            end)

            it("search action requires query", function()
                local result, err = kb_read.handler({ action = "search" })
                test.is_nil(result)
                test.not_nil(err)
            end)

            it("search action rejects empty query", function()
                local result, err = kb_read.handler({ action = "search", query = "" })
                test.is_nil(result)
                test.not_nil(err)
            end)

            it("get action requires node_id", function()
                local result, err = kb_read.handler({ action = "get" })
                test.is_nil(result)
                test.not_nil(err)
            end)

            it("list_kbs returns result", function()
                local result, err = kb_read.handler({ action = "list_kbs" })
                test.is_nil(err)
                test.not_nil(result)
                test.eq(type(result), "string")
            end)

            it("list returns result", function()
                local result, err = kb_read.handler({ action = "list" })
                test.is_nil(err)
                test.not_nil(result)
                test.eq(type(result), "string")
            end)
        end)

        describe("kb_write", function()
            it("requires action parameter", function()
                local result, err = kb_write.handler({})
                test.is_nil(result)
                test.not_nil(err)
            end)

            it("rejects unknown action", function()
                local result, err = kb_write.handler({ action = "invalid" })
                test.is_nil(result)
                test.not_nil(err)
            end)

            it("create requires title", function()
                local result, err = kb_write.handler({ action = "create", node_type = "pattern" })
                test.is_nil(result)
                test.not_nil(err)
            end)

            it("create requires node_type", function()
                local result, err = kb_write.handler({ action = "create", title = "Test" })
                test.is_nil(result)
                test.not_nil(err)
            end)

            it("create rejects empty title", function()
                local result, err = kb_write.handler({ action = "create", title = "", node_type = "pattern" })
                test.is_nil(result)
                test.not_nil(err)
            end)

            it("update requires node_id", function()
                local result, err = kb_write.handler({ action = "update", title = "Updated" })
                test.is_nil(result)
                test.not_nil(err)
            end)

            it("delete requires node_id", function()
                local result, err = kb_write.handler({ action = "delete" })
                test.is_nil(result)
                test.not_nil(err)
            end)
        end)
    end)
end

local run = test.run_cases(define_tests)
return { define_tests = run }
