local test = require("test")
local state_reader = require("state_reader")

local function define_tests()
    describe("State Reader", function()
        describe("entry reader", function()
            it("for_branch returns a reader without error", function()
                local reader, err = state_reader.for_branch("main")
                test.is_nil(err)
                test.not_nil(reader)
            end)

            it("for_branch defaults to main when no argument given", function()
                local reader, err = state_reader.for_branch()
                test.is_nil(err)
                test.not_nil(reader)
            end)

            it("all returns a table", function()
                local reader = state_reader.for_branch("main")
                local results, err = reader:all()
                test.is_nil(err)
                test.not_nil(results)
                test.eq(type(results), "table")
            end)

            it("count returns a number", function()
                local reader = state_reader.for_branch("main")
                local count, err = reader:count()
                test.is_nil(err)
                test.not_nil(count)
                test.eq(type(count), "number")
            end)

            it("exists returns a boolean", function()
                local reader = state_reader.for_branch("main")
                local exists, err = reader:exists()
                test.is_nil(err)
                test.not_nil(exists)
                test.eq(type(exists), "boolean")
            end)

            it("one returns nil or a table", function()
                local reader = state_reader.for_branch("main")
                local entry, err = reader:one()
                test.is_nil(err)
                local t = type(entry)
                test.is_true(t == "nil" or t == "table")
            end)

            it("limit constrains results", function()
                local reader = state_reader.for_branch("main")
                local limited = reader:limit(2)
                local results, err = limited:all()
                test.is_nil(err)
                test.not_nil(results)
                test.is_true(#results <= 2)
            end)

            it("with_namespaces filters correctly", function()
                local reader = state_reader.for_branch("main")
                local filtered = reader:with_namespaces("keeper.mcp")
                local results, err = filtered:all()
                test.is_nil(err)
                test.not_nil(results)
                test.eq(type(results), "table")
            end)

            it("with_kinds returns a reader", function()
                local reader = state_reader.for_branch("main")
                local filtered = reader:with_kinds("document")
                test.not_nil(filtered)
                local results, err = filtered:all()
                test.is_nil(err)
                test.eq(type(results), "table")
            end)

            it("with_entries returns a reader", function()
                local reader = state_reader.for_branch("main")
                local filtered = reader:with_entries("some-id")
                test.not_nil(filtered)
                local results, err = filtered:all()
                test.is_nil(err)
                test.eq(type(results), "table")
            end)

            it("include_deleted returns a reader", function()
                local reader = state_reader.for_branch("main")
                local with_deleted = reader:include_deleted()
                test.not_nil(with_deleted)
                local results, err = with_deleted:all()
                test.is_nil(err)
                test.eq(type(results), "table")
            end)

            it("include_chunks returns a reader", function()
                local reader = state_reader.for_branch("main")
                local with_chunks = reader:include_chunks()
                test.not_nil(with_chunks)
                local results, err = with_chunks:all()
                test.is_nil(err)
                test.eq(type(results), "table")
            end)

            it("include_attributes returns a reader", function()
                local reader = state_reader.for_branch("main")
                local with_attrs = reader:include_attributes()
                test.not_nil(with_attrs)
                local results, err = with_attrs:all()
                test.is_nil(err)
                test.eq(type(results), "table")
            end)

            it("with_attributes accepts a filter table", function()
                local reader = state_reader.for_branch("main")
                local filtered = reader:with_attributes({ status = "active" })
                test.not_nil(filtered)
                local results, err = filtered:all()
                test.is_nil(err)
                test.eq(type(results), "table")
            end)

            it("chaining methods returns new reader instances", function()
                local original = state_reader.for_branch("main")
                local chained = original:with_kinds("document"):with_namespaces("keeper"):limit(5)
                test.not_nil(chained)
                local results, err = chained:all()
                test.is_nil(err)
                test.eq(type(results), "table")
            end)

            it("fluent chaining does not mutate original reader", function()
                local original = state_reader.for_branch("main")
                local with_limit = original:limit(1)
                local with_kinds = original:with_kinds("document")

                -- original must remain unmodified by the chained calls
                local orig_results, err1 = original:all()
                test.is_nil(err1)
                test.not_nil(orig_results)

                local limit_results, err2 = with_limit:all()
                test.is_nil(err2)
                test.is_true(#limit_results <= 1)

                local kind_results, err3 = with_kinds:all()
                test.is_nil(err3)
                test.not_nil(kind_results)

                -- count from original should be >= limited count
                test.is_true(#orig_results >= #limit_results)
            end)
        end)

        describe("edge reader", function()
            it("for_edges returns an edge reader without error", function()
                local reader, err = state_reader.for_edges("main")
                test.is_nil(err)
                test.not_nil(reader)
            end)

            it("for_edges defaults to main when no argument given", function()
                local reader, err = state_reader.for_edges()
                test.is_nil(err)
                test.not_nil(reader)
            end)

            it("all returns a table", function()
                local reader = state_reader.for_edges("main")
                local results, err = reader:all()
                test.is_nil(err)
                test.not_nil(results)
                test.eq(type(results), "table")
            end)

            it("with_sources returns a reader", function()
                local reader = state_reader.for_edges("main")
                local filtered = reader:with_sources("src-id")
                test.not_nil(filtered)
                local results, err = filtered:all()
                test.is_nil(err)
                test.eq(type(results), "table")
            end)

            it("with_targets returns a reader", function()
                local reader = state_reader.for_edges("main")
                local filtered = reader:with_targets("tgt-id")
                test.not_nil(filtered)
                local results, err = filtered:all()
                test.is_nil(err)
                test.eq(type(results), "table")
            end)

            it("with_edge_types returns a reader", function()
                local reader = state_reader.for_edges("main")
                local filtered = reader:with_edge_types("depends_on")
                test.not_nil(filtered)
                local results, err = filtered:all()
                test.is_nil(err)
                test.eq(type(results), "table")
            end)

            it("limit constrains results", function()
                local reader = state_reader.for_edges("main")
                local limited = reader:limit(3)
                local results, err = limited:all()
                test.is_nil(err)
                test.not_nil(results)
                test.is_true(#results <= 3)
            end)

            it("chaining methods returns new reader instances", function()
                local reader = state_reader.for_edges("main")
                local chained = reader:with_sources("a"):with_edge_types("link"):limit(10)
                test.not_nil(chained)
                local results, err = chained:all()
                test.is_nil(err)
                test.eq(type(results), "table")
            end)

            it("fluent chaining does not mutate original reader", function()
                local original = state_reader.for_edges("main")
                local with_limit = original:limit(1)
                local with_types = original:with_edge_types("depends_on")

                local orig_results, err1 = original:all()
                test.is_nil(err1)
                test.not_nil(orig_results)

                local limit_results, err2 = with_limit:all()
                test.is_nil(err2)
                test.is_true(#limit_results <= 1)

                local type_results, err3 = with_types:all()
                test.is_nil(err3)
                test.not_nil(type_results)

                test.is_true(#orig_results >= #limit_results)
            end)

            it("entry-only methods are no-ops on edge reader", function()
                local reader = state_reader.for_edges("main")
                local same = reader:with_kinds("document")
                test.not_nil(same)
                local results, err = same:all()
                test.is_nil(err)
                test.eq(type(results), "table")
            end)
        end)
    end)
end

local run = test.run_cases(define_tests)
return { define_tests = run }
