version: "1.0"
namespace: keeper.integrate.discovery

entries:
  - name: migration_handler
    kind: function.lua
    meta:
      type: integration.handler
      title: Execute Migrations
      icon: tabler:database-import
      comment: Executes database migrations
      order: 100
      handles:
        meta.type: "migration"
      operations: [ "up", "down" ]
      mode: batch
    source: file://migration_handler.lua
    modules: [ json, registry ]
    imports:
      runner: wippy.migration:runner
    method: handler

  - name: env_variable_handler
    kind: function.lua
    meta:
      type: integration.handler
      title: Mount Environment Variables
      icon: tabler:variable
      order: 200
      handles:
        kind: "env.variable"
      operations: [ "up", "down" ]
      mode: batch
    source: file://env_variable_handler.lua
    modules: [ json ]
    method: handler

  - name: view_handler
    kind: function.lua
    meta:
      type: integration.handler
      title: Validate Views
      icon: tabler:browser-check
      comment: Renders and validates view entries
      order: 300
      handles:
        meta.type: "view.page"
      operations: [ "up", "down" ]
      mode: batch
    source: file://view_handler.lua
    modules: [ json ]
    imports:
      renderer: wippy.views:renderer
    method: handler